### ISSUE TITLE
MMM-GoogleShoppingList doesn't work anymore

### ISSUE THREAD

**Issue by ChristophLudwig** [eouia/MMM-GoogleShoppingList#5]
Hi

I have tested the ShoppingList module successfully in autumn and wanted to reactivate it now. I get the following error:

----------------------------
/home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_helper.js:54
    async function get(browserOption) {
          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:17)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
Whoops! There was an uncaught exception...
/home/pi/MagicMirror/modules/MMM-GoogleShoppingList/node_helper.js:54
    async function get(browserOption) {
          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:17)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

--------------------------

Internet connection is ok.

**Comment by eouia** [comment]
Hmmm weird. Was that working but not now?
Your error messages say somewhat old version of node you are using. But if so, how it could work at that time?

**Comment by ChristophLudwig** [comment]
Yes, it had worked. Do you have any idea how i can fix this with this "old version of node"? (I am not an expert)

**Comment by eouia** [comment]
What is your OS and device? (e.g: Raspbian Stretch, RPI 3B+...)
And what is your node version? You can check it with `node -v`

**Comment by eouia** [comment]
`async` is supported after node 7.6 (current stable version is 8.11)
You can use `nvm` to update and control node version. (https://github.com/creationix/nvm)

**Comment by ChristophLudwig** [comment]
RPI 3B+
OS: Raspbian GNU/Linux 9 (stretch)
node version: v9.11.2

**Comment by eouia** [comment]
Weird. You node version is enough. But that error would happen when node version is low.

**Comment by ChristophLudwig** [comment]
Alternatively, I get the message that my config file has an error. "Please correct syntax errors"

If I comment the part with MMM-GoogleShoppingList out it works

**Comment by ChristophLudwig** [comment]
Is there an easy way to make a clear, complete uninstall of this whole magic mirror thing? (incl. npm?)

**Comment by eouia** [comment]
Best way is... format and burn new SD image? :D Sorry, I'm not an expert about that kind.

**Comment by eouia** [comment]
I'll close this issue coz there is no other feedback. Have a nice day.
