### ISSUE TITLE
Puppeteer needs to be updated to latest version

### ISSUE THREAD

**Issue by jszuslik** [eouia/MMM-GoogleShoppingList#7]
I was getting the following error
`[GSL] Trying to login
[GSL] Cookies are saved.
[GSL] Landed on the target page. Trying to get list
(node:49777) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/ExecutionContext.js:161:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/helper.js:110:27)
    at ExecutionContext.evaluate (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluate (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/Page.js:782:43)
    at Page.<anonymous> (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_modules/puppeteer/lib/helper.js:111:23)
    at get (/Users/jszuslik/Personal/electron/mm2/MagicMirror/modules/MMM-GoogleShoppingList/node_helper.js:101:29)
(node:49777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:49777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I updated the puppeteer version to 1.15.0 and rebuilt. This resolved the issue.

**Comment by eouia** [comment]
Thanks for notice. I apply this info on `package.json`.
